services:
  - type: web
    name: obsidian-linker
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:fastapi_app --host 0.0.0.0 --port $PORT
